[package]
name = "practice"
version = "0.1.0"
edition = "2021"
readme = "README.md"

[dependencies]
futures = "0.3.31"
reqwest = "0.12.15"
tokio = { version = "1.45.0", features = ["full"] }

[build-dependencies]
bindgen = "0.59"
cc = "1"
